services:
# simulator
  simulator:
    build:
      context: .
    container_name: spring-simulator
    ports:
      - "8085:8080"
    networks:
      - uspace-network
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s
    restart: "on-failure:3"

networks:
  uspace-network:
    driver: bridge