package com.aeroflux.drone.domain.model;

public enum DroneFlightMode {
    FLIGHT_COMPLETED, NORMAL_FLIGHT, EMERGENCY_LANDING, REROUTE_FLIGHT, EMERGENCY_LANDING_REQUEST, LANDING_REQUEST, ALTERNATIVE_DESTINATION_REQUEST
}
