services:
# Weather
  weather:
    build:
      context: .
    container_name: spring-weather
    environment:
      SPRING_PROFILE: ${SPRING_PROD_PROFILE}
    ports:
      - "8084:8080"
    networks:
      - uspace-network
    volumes:
      - weather-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s
    restart: "on-failure:3"

networks:
  uspace-network:
    driver: bridge

volumes:
  weather-data:
    driver: local