name: Build & Push Docker images to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versione immagine (es: v1.2.3 o lascia vuoto per latest)'
        required: false
        default: latest

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [drone-identification, geo-awareness]

    permissions:
      contents: read
      packages: write # necessario per pushare su GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ask for version tag
        id: ask-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            VERSION=latest
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.project }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ env.VERSION }}
